#!/bin/sh
#TODO: Move what we can out to browse and play, where we can. 
#      e.g. *youtu* play, then handle the oddities in play
#      gopher* browse
yt() {
	play "$1" &
	exit 0
}

to() {
	browse "$1" &
	exit 0
}

asci() {
	st -e asciinema play "$1" &
	exit 0
}

case "$@" in
	*bell-labs.com*) 	url="$(echo "$1" | sed 's/.\+com//')"
				to "http://9p.io$url" ;;
	*youtube.com/watch*)	yt "$@" ;;
	*youtu.be*)		yt "$@" ;;
	*youtube.com/v/*)	yt "$@" ;;
	ytdl*)			yt "$@" ;;
	*youtube.com/play*)	yt "$@" ;;
	*vimeo*)		yt "$@" ;;
	*youtube.com/channel*)	exec "$XDG_DATA_HOME"/dsearch/yt "$@" ;;
	*.mp3*)			yt "$@" ;;
	*webm)			yt "$@" ;;
	*mkv)			yt "$@" ;;
	*gifv\?)		yt "$@" ;;
	
	gopher://*)		exec st -e cgo "$1" && exit 0 ;;
	
	*gehidore.net/t/*)	URL=`echo $@ | sed 's|/t||p'`
				asci "$URL" ;;
	*ptpb.pw/t/*)		URL=`echo $@ | sed 's|/t||p'`
				asci "$URL" ;;
	*asciinema*)		asci "$@" 	;;
	ISBN*)			URL=`echo $@ | awk '{print $2}'`
				to "https://duckduckgo.com?q=!a%20$URL" ;;
		
	*ptpb.pw/*/*) 		URL=`echo $@ | cut -b 1-20`			
				exec plumber "$URL" &
				exit 0;; 
	ftp://*)		to "$@" ;;
		
esac

exit 1
