#!/bin/bash
compton --config ~/local/cfg/compton/config &
~/local/cfg/wmutils/watcher &
dunst &
feh --bg-scale ~/media/backgrounds/$(( $(( RANDOM % $(find ~/media/backgrounds | wc -l) )) + 1 )).png --no-fehbg &
exec dwm
