#!/bin/bash

# Trying this out!
xhost +si:localuser:"$USER"

mpd &
sxhkd &
xcmenu &
compton &
#syncthing &
colortempd -t 4000 &
~/local/cfg/wmutils/bar & 
GMusicProxy --config ~/local/cfg/gmusicproxy/config &
#x11fs -o auto_unmount ~/run/x11fs &
exec ~/local/cfg/wmutils/watcher 
