#!/usr/bin/env bash

readonly optsfile=$XDG_CONFIG_HOME/dmenu/dmenucolors
readonly datadir="$XDG_DATA_HOME"

read -r KEY < "$datadir/youtube/key"

create_playlist() {
    local -i number=1
    while {
        IFS=$'\n' read -r key
        read -r value
    } do
        printf -- '%s\n%s\n' "Title$number=$key" "File$number=https://www.youtube.com/watch?v=${value//\"/}" >> "$datadir/mpv/$title.pls"
        number=$(( number + 1 ))
    done <<< "$( curl -s "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&key=$KEY&playlistId=$url&maxResults=50" | jshon -CQ -e items -a -e snippet -e title -upe resourceId -e videoId -u)"
    printf -- '%b' "NumberOfEntries=$(( number - 1 ))" >> "$datadir/mpv/$title.pls"
}

# Main

read -r url < /tmp/tmpplaylist

[[ -s $optsfile ]] && source "$optsfile"

opts+=( -l 1 -p "Playlist name: " )

title=$(printf '%s' "" | dmenu "${opts[@]}")

[[ ! "$title" ]] && exit 0

printf -- '%s\n' "[playlist]" > "$datadir/mpv/$title.pls"

create_playlist
