#!/usr/bin/env bash
# Appends to playlists, or creates new ones.

readonly datadir=${XDG_DATA_HOME:-$HOME/local/share}/mpv

create_menu() {
    cd "$datadir" || exit 1
    for file in *; do
        printf '%s\n' "$file"
    done 
}

append_selection() {
    create_menu | dmenu -p "Append to: "
}

fetch_number() {
    declare -i number
    local v k
    while IFS='=' read -r k v; do
        case "$k" in
            NumberOfEntries*)
                number="$v" ;;
        esac
    done < "$1"
    printf '%s' "$(( number=number + 1))"
}

fetch_path() {
    echo '{ "command": ["get_property", "path"] } ' | socat - /tmp/mpvsock
}

fetch_title(){
    echo '{ "command": ["get_property", "media-title"] } ' | socat - /tmp/mpvsock
}


# Main

if [[ $1 == https://www.youtube.com/channel/* ]]; then
	# make our directory
	path="$(echo "" | dmenu -p "Enter title: ")"
	mkdir -p "$XDG_CACHE_HOME/rss/$path"
	echo "https://www.youtube.com/feeds/videos.xml?channel_id=${1#*channel\/}" > "$XDG_CACHE_HOME/rss/$path"/url
	exit 0
fi

current="$(fetch_path "path"| jshon -e data -u)"
title="$(fetch_title "media-title" | jshon -e data -u)"
title=$(printf '%s' "$title" | dmenu -l 1 -p Title)
file=$(append_selection)

if [[ ! -s "$datadir/$file" ]]; then
    file="$file".pls
    (cd "$datadir" || exit 1
    printf '%s\n%s' "[playlist]" "NumberOfEntries=0" > "$file")
fi

number=$(fetch_number "$datadir/$file")

# Make sure we have a selection
if [[ $file && $current && $title && $number ]]; then
    (cd "$datadir" || exit 1
    sed -i '/NumberOfEntries=[0-9]*[0-9]/d' "$file"
    printf -- '%s\n%s\n%s\n' "Title$number=$title" "File$number=${current/*v=/ytdl:\/\/}" "NumberOfEntries=$number" >> "$file")
fi
