#!/usr/bin/env bash
# Write/remove a task to do later.

readonly optsfile="$XDG_CONFIG_HOME"/dmenu/bemenucolors

TASKFILE="$XDG_CACHE_HOME/todo/$1"
HEIGHT=$(wc -l < "$TASKFILE")
PROMPT="Add/delete a task"

menu() {
  bemenu -l "$HEIGHT" "${opts[@]}" -p "$PROMPT: " < "$TASKFILE"
}

loop_run() {
  while true; do
    result=$(menu)
    # Return to main program on exit
    [[ ! $result ]] && exec "$XDG_DATA_HOME"/dsearch/todo
    if grep "$result" "$TASKFILE"; then
      sed -i "s/$result//g" "$TASKFILE"
      HEIGHT=$((HEIGHT-1))
    else
      printf '%s\n' "$result" >> "$TASKFILE"
      HEIGHT=$(wc -l < "$TASKFILE")
    fi
    sed -i '/^$/d' "$TASKFILE"
  done
}

## Main

[[ -s $optsfile ]] && source "$optsfile"

loop_run
