#!/bin/bash

# Trying this out!
xhost +si:localuser:"$USER"
setxkbmap -option caps:escape

xrdb -merge ~/local/cfg/x11/Xresources
sxhkd -m -1 &
xcmenu &
hsetroot -fill ~/local/cfg/x11/calvin.jpg -tint "$(xrdb -query ~/local/cfg/x11/Xresources | awk '/color0/{print $NF}')"
inotifybar & 
exec hwwm 
