#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# toggle the fullscreen state of a window
# depends on: focus.sh

FSFILE=${FSFILE:-/tmp/fwin}
X11=${X11FSDIR:-~/run/x11}
SIZE=$XDG_CONFIG_HOME/x11fs/size

if test -f $FSFILE; then
    cat $FSFILE | xargs -n 5 wtp
    rm -f $FSFILE
else
    wattr xywhi $1 > $FSFILE
    sed -ne 's/fulh=//p' $SIZE > $X11/$1/geometry/height
    sed -ne 's/fulw=//p' $SIZE > $X11/$1/geometry/width
    sed -ne 's/gaps=//p' $SIZE > $X11/$1/geometry/x
    sed -ne 's/gaps=//p' $SIZE > $X11/$1/geometry/y
    chwso -r "$1"
    printf '%s\n' "$1" > $X11/focused    
fi

"$XDG_CONFIG_HOME"/x11fs/focus $1
