Plug 'romainl/Apprentice'
Plug 'Yggdroot/indentLine'
Plug 'benekastah/neomake'
Plug 'cespare/vim-toml' 
Plug 'tpope/vim-fugitive'
Plug 'hsanson/vim-android'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
