#!/bin/bash

# Trying this out!
setxkbmap -option caps:escape
setxkbmap dvorak
xrdb -merge ~/local/cfg/x11/Xresources
redshift &
sxhkd -m -1 &
xcmenu &
hsetroot  -center ~/local/x11/background.png -tint "$(xrdb -query | awk '/desktop/{print $NF}')"
inotifybar &
exec hwwm
