#!/bin/sh --

# These options will go away with system-wide config
setxkbmap -option caps:escape
setxkbmap dvorak
compton &

# Dual monitor for now
xrandr --auto --output DP1 --right-of DP3 --output HDMI1 --left-of DP3 --output DP3 --primary
hsetroot -solid '#787878'

## Run
exec hwwm
