#!/bin/sh --

# These options will go away with system-wide config
setxkbmap -option caps:escape
setxkbmap dvorak

# Clipboard menu and backlight automation
## Run
compton -b &
feh --bg-scale --no-xinerama Downloads/5760x1080-2915477-triple-screen-mountain-snow-polyscape___mixed-wallpapers.jpg &

exec hwwm

