#!/usr/bin/env bash
# Create menu based on URLs and titles.

readonly datadir=${XDG_DATA_HOME:-$HOME/local/share}
readonly optsfile="$XDG_CONFIG_HOME"/dmenu/bemenucolors

create_menu() {
    sed -n -e 's/^.*Title[0-9]\+=//p' "$1"
}

get_selection() {
    opts+=( -p "Select video" -l 10 )
    create_menu "$datadir/mpv/$1" | bemenu "${opts[@]}"
}

get_position() {
    awk -v result="$2" 's=index($0,result) { print int((NR-1)/2) }' "$datadir/mpv/$1"
}

get_playlist() {
	echo '{"command": ["get_property", "playlist-name"] }' | socat - /tmp/mpvsock | jshon -e data    
}

# Main

[[ -s $optsfile ]] && source "$optsfile"

result=$(get_selection "$1")

[[ ! $result ]] && exit 0

result=$(get_position "$1" "$result")

exec play "$datadir/mpv/$1" --playlist-pos="$result"