#!/usr/bin/env bash
## List or download album playlists

# Gmusicproxy host IP
readonly host=localhost

# Gmusicproxy default port
readonly port=9999

readonly optsdir="$XDG_CONFIG_HOME"/dmenu/bemenucolors
readonly url=http://$host:$port

get_id() {
  curl -s "$url/search_id?type=artist&artist=${1//\ /%20}"
}

discography() {
  curl -s "$url/get_discography_artist?id=$(get_id "$1")&format=text" > "$tmp/$1"
}

build() {
  while IFS="|" read -r title year link; do
    printf '%s - %s\n' "$year" "$title"
  done
}

search_artist() {
  [[ -s $optsdir ]] && source "$optsdir" 
  discography "${1//\ %20}"

  opts+=(-p "Select album" -l 10)
  mpc clear
  build < "$tmp/$1" | sort -u | tac | bemenu "${opts[@]}" | while read -r result; do
    [[ ! $result ]] && break
    result=$(grep -F "${result#*-\ }" "$tmp/$1")
    curl -s "$url/get_album?id=${result##*id=}" > "$XDG_CONFIG_HOME/mpd/playlists/$1 - ${result%%|*}.m3u"
    mpc load "$1 - ${result%%|*}"
  done
}

search_album() {
  artist="${1%\ -*}"
  title="${1#*-\ }"
  mpc clear
  curl -s "$url/get_by_search?type=album&artist=${artist//\ /%20}&title=${title//\ /%20}" > "$XDG_CONFIG_HOME/mpd/playlists/$1.m3u" 
  [[ ! -s $XDG_CONFIG_HOME/mpd/playlists/$1.m3u ]]
  mpc load "$1"

}



case "$@" in
  *\ -\ *) search_album  "$@" ;;
  *)       tmp=$(mktemp -d)
           search_artist "$@" ;;
esac

mpc random off
mpc play
