#!/usr/bin/env bash
# Google Books search handler

readonly progn=gbookhandler
readonly optsfile="$XDG_CONFIG_HOME"/dmenu/dmenucolors

# For Json
readonly TMPDIR="${TMPDIR:-/tmp}"

fetch_json() {	
   curl -s "https://www.googleapis.com/books/v1/volumes?q=${@// /%20}&maxResults=40&orderBy=relevance" > $TMPDIR/gbook.json
}

parse_info() {
	# we need to pull out the URL in this same call, to stdout. 
        jshon -CQ -e items -a -e volumeInfo -e title -upe authors -e 0 -uppe infoLink < "$TMPDIR"/gbook.json        
}

create_menu() {
	local key
	for key in "${!menu[@]}"; do
	        # iterate through keys
		printf '%s' "$key" 		
	done
}

get_selection() {
  opts+=(-ia top-gapless -is 250x250 -l 10 -p "Select book: " )
	create_menu | dmenu "${opts[@]}"
}

populate_info() { # title pagecount isbn # isbn #
  while {
    read -r title
	  read -r authors
	  read -r infolink
	} do
	  menu["$authors - $title"]=1
	  info["$authors - $title"]="${infolink//\\/}"
  done
}

process_selection() { # global token
	url="${info[$1]}"
	exec browse "${url//\"/}"
}


# Main
declare -A menu info

[[ -s $optsfile ]] && source "$optsfile"

fetch_json "$@" 

populate_info < <(parse_info)
wait

results="$(get_selection)"
if [[ "$results" ]]; then
	process_selection "$results"
fi
