#!/usr/bin/env bash

# Code search using dmenu (single string)
# Requires dmenu, ag

readonly optsfile=$XDG_CONFIG_HOME/dmenu/dmenucolors


get_selection() {
    opts+=( -l 10 -p "Select file to edit: " )
    ag --vimgrep "$1" | dmenu "${opts[@]}"
}

# Main

# Configuration

[[ -s $optsfile ]] && source "$optsfile"

result=$(get_selection "$1")

# Verify a selection was made
if [[ $result ]]; then
    subres="${result#*:}"
    exec st -t NVIM -e nvim +"${subres%%:*}" "$HOME/${result%%:*}"
fi
