#!/usr/bin/env bash

# Code search using dmenu (single string)
# Requires dmenu, ag


get_selection() {
    ag --vimgrep "$1" | dmenu -p "Select file: "
}

# Main

# Configuration

result=$(get_selection "$1")

# Verify a selection was made
if [[ $result ]]; then
    subres="${result#*:}"
    exec st -t NVIM -e nvim +"${subres%%:*}" "$HOME/${result%%:*}"
fi
