#!/usr/bin/env bash
# Code search using bemenu (single string)
# Requires bemenu, tree, neovim, and python

readonly confdir=${XDG_CONFIG_HOME:-$HOME/local/cfg}
readonly optsfile=$confdir/dmenu/bemenucolors
readonly terminal=/usr/bin/termite

# Whilelist of locations to search
readonly locations=( ~/programming \
                     ~/local/cfg   \
                     ~/local/bin   \
                     ~/local/share
);

get_selection() {
    grep -Iri "$1" "${locations[@]}" --exclude="*.git" | bemenu -l 10 "${opts[@]}" -p "Edit"
}

# Main

# Configuration
# https://github.com/halfwit/dotfiles/blob/master/.config/dmenu/font
if [[ -s $confdir/dmenu/font ]]; then
    read -r font < "$confdir"/dmenu/font
fi

if [[ $font ]]; then
    opts+=(-fn "$font")
fi

if [[ -s $optsfile ]]; then
    source "$optsfile"
fi

# Chain multiple arguments like.*this for grep
token="$*"
result=$(get_selection "${token// /.\*}")

# Verify a selection was made
if [[ $result ]]; then
    nvim-run "${result%:*}"
fi
