#!/usr/bin/env bash

varless() {
    echo "$1" | less
}

result=$(curl -s dict://dict.org/d:"$1":wn | awk '/151/{flag=1;next}/250/{flag=0}flag') 

if [[ $result ]]; then
  st -t dict -e varless "$result"
else
  exec browse "!def $1"
fi
