#!/usr/bin/env bash

tmp=$(mktemp)
curl -s dict://dict.org/d:"$1":wn | awk '/151/{flag=1;next}/250/{flag=0}flag' > "$tmp" 

if [ -f $tmp ]; then
  st -t dict -e less "$tmp"
else
  exec browse "!def $1"
fi
