#!/usr/bin/env bash

result=$(curl -s dict://dict.org/d:"$1":wn | awk '/151/{flag=1;next}/250/{flag=0}flag' | head -n -1)

if [[ "$result" ]]; then
   exec notify-send "$result"
fi
exec vimb-run "!def $1"
