#!//bin/sh

## Requires
# https://github.com/jarun/googler
# dmenu

fetch() {
		googler "$1" --json -x -n 25 | jshon -a -e title -upe url -u
}

chunk() {
		while {
				read -r title
				read -r url
		} do
				printf '%s\n' "$title :: $url"
		done
}

fetch "$1" | chunk | dmenu -p "Select result: " | sed 's/^.*:: //' | xe plumber
