#!/usr/bin/env bash
# Google Books search handler

readonly progn=gbookhandler
readonly confdir="$XDG_CONFIG_HOME"
readonly optsfile="$confdir"/dmenu/bemenucolors

# For Json
readonly TMPDIR="${TMPDIR:-/tmp}"

fetch_json() {	
   curl -s "https://www.googleapis.com/books/v1/volumes?q=${@// /%20}&maxResults=40&orderBy=relevance" > $TMPDIR/gbook.json
}

parse_info() {
	# we need to pull out the URL in this same call, to stdout. 
        jshon -CQ -e items -a -e volumeInfo -e title -upe authors -e 0 -uppe infoLink < "$TMPDIR"/gbook.json        
}

create_menu() {
	local key
	for key in "${!menu[@]}"; do
	        # iterate through keys
		printf '%s' "$key" 		
	done
}

get_selection() {

	create_menu | bemenu -l 10 "${opts[@]}" -p "Select book"
}

populate_info() { # title pagecount isbn # isbn #
  while {
    read -r title
	  read -r authors
	  read -r infolink
	} do
	  menu["$authors - $title"]=1
	  info["$authors - $title"]="${infolink//\\/}"
  done
}

process_selection() { # global token
	url="${info[$1]}"
	vimb-run "${url//\"/}"
}


# Main
declare -A menu info

if [[ -s $confdir/dmenu/font ]]; then
  read -r font < "$confdir"/dmenu/font
fi

if [[ $font ]]; then
  opts+=(-fn "$font")
fi

if [[ -s $optsfile ]]; then
  source "$optsfile"
fi

fetch_json "$@" 

populate_info < <(parse_info)
wait

results="$(get_selection)"
if [[ "$results" ]]; then
	process_selection "$results"
fi
