#!/usr/bin/env bash

grep / <<< $1 && exec browse "https://github.com/$1"


. $XDG_CONFIG_HOME/dmenu/dmenucolors

result=$(curl -s "https://api.github.com/search/users?q=$1")

count=$(printf '%s\n' "$result" | jshon -e total_count -u)

if [ $count -gt 1 ]; then
  opts+=(-l 10 -p "Select user")
  result=$(printf '%s\n' "$result" | jshon -e items -a -e login -u | dmenu "${opts[@]}")
else
  result=$(printf '%s\n' "$result" | jshon -e items -a -e login -u)
fi

repo=$(curl -s "https://api.github.com/search/repositories?q=user:$result") 
opts+=(-l 10 -p "Select repository")
url=$(printf '%s\n' "$repo" | jshon -e items -a -e name -u | dmenu "${opts[@]}") 

[ $url ] && browse "https://github.com/$result/$url"
