#!/usr/bin/env bash

# Database of bookmarks for quick linking
# Use namespacing in the title (dead simple, yay!!)
readonly optsfile=$XDG_CONFIG_HOME/dmenu/dmenucolors
readonly datadir="$XDG_DATA_HOME"
readonly pics="$HOME"/media/pictures

get_selection() {
  find "$datadir"/bookmark -type f -not -path '*/\.*'
  find "$datadir"/mpv -type f -not -path '*/\.*'
  find "$pics" -type f -not -path '*/\.*'
}

extract_links() {
  local input
  while read -r input; do
    case "$input" in
      *bookmark*)
        read -r url < "$input"
        printf '%s\n' "${input##*bookmark\/}"
        ;;
      *mpv*)
        input="${input/.pls/}"
        printf '%s\n' "video - ${input##*mpv\/}"
        ;;
      *pictures*) 
        printf 'IMG:%q\t%s\n' "$pic/$input" "image - ${input##*pictures\/}"
        ;;
    esac
  done
}

handle_mpv() {
  local result
  result=$(sed -n -e 's/^Title[0-9]=//p' < "$datadir/mpv/${1##*-\ }.pls" | dmenu "${opts[@]}" -p "Select title") 
  
  # If no selection is made, return to this program
  [[ ! $result ]] && exec "$datadir/dsearch/link"
  
  sed -n -e "/$result/ { n; s/^File[0-9]=//p }" < "$datadir/mpv/${1#*-\ }.pls"
}

[[ -s $optsfile ]] && source "$optsfile"

opts+=( -l 10 -p "Select bookmark" )
result=$(get_selection | sort -u | extract_links | dmenu "${opts[@]}")

case $result in
  video*) result="$(handle_mpv "$result")" ;;
  image*) result="$(exiftool "$pics/${result#*-\ }" | awk '/Comment/ { print $NF }')" ;;
  *) read -r result < "$datadir/bookmark/$result"
esac

[[ $result ]] && exec xcmenu -ic "$result"
