#!/usr/bin/env bash
# generate menu of current playlists, wait for input to start up !radio or current playlist
readonly optsdir="$XDG_CONFIG_HOME"/dmenu/bemenucolors

if ! pgrep mpd; then
  mpd &
fi

# Clear out currently playing lists
mpc clear
mpc random off
[[ -s $optsdir ]] && source "$optsdir"
opts+=(-p "Select playlist or enter radio station" -l 10)
mpc lsplaylists | bemenu "${opts[@]}" | while read -r result; do
  # If playlist exists, load everything
  if ! mpc load "$result"; then
    case "$result" in
      radio\ -\ *) "$XDG_DATA_HOME"/dsearch/radio "$result" ;;
      *\ -\ *)     "$XDG_DATA_HOME"/dsearch/album "$result" ;;
    esac 
  fi
done
mpc play
