#!/usr/bin/env bash
# generate menu of current playlists, wait for input to start up !radio or current playlist
readonly optsdir="$XDG_CONFIG_HOME"/dmenu/dmenucolors

if ! pgrep mpd; then
  mpd &
fi

# Clear out currently playing lists
mpc clear
mpc random off
[[ -s $optsdir ]] && source "$optsdir"
opts+=(-p "Select playlist" -l 10 -i)
mpc lsplaylists | dmenu "${opts[@]}" | while read -r result; do
  # If playlist exists, load
  mpc load "$result"
done
mpc play
