#!/bin/sh
tmp=`mktemp`

artist=`printf "$1" | cut -d '-' -f1 | sed 's/ /+/g'`
title=`printf "$1" | cut -d '-' -f2 | sed 's/ /+/g'`

if pgrep mpg123; then
	artist=`mpc current --format "%artist%" | sed 's/ /+/g'`
	title=`mpc current --format "%title%" | sed 's/ /+/g/'` 
fi 

curl -s "https://makeitpersonal.co/lyrics?artist=$artist&title=$title" > "$tmp"

# Fire off results
st -t lyrics -e less "$tmp"
rm -rf "$tmp"
