#!/usr/bin/env bash

readonly optsfile="$XDG_CONFIG_HOME"/dmenu/bemenucolors

handle_result() {
   local width
   #Coloration, and match width
   width=$(tput cols)
   [[ $width -gt $MANWIDTH ]] && \
   exec env LESS=-RX \
   MANWIDTH="$width" \
   LESS_TERMCAP_mb=$'\E[01;31m' \
   LESS_TERMCAP_md=$'\E[01;38;5;74m' \
   LESS_TERMCAP_me=$'\E[0m' \
   LESS_TERMCAP_se=$'\E[0m' \
   LESS_TERMCAP_so=$'\E[38;5;246m' \
   LESS_TERMCAP_ue=$'\E[0m' \
   LESS_TERMCAP_us=$'\E[04;38;5;146m' \
   st -t float -e man "$1" "$2"
}

get_selection() {
  opts+=(-l 10 -p "Manual: ")
  apropos "$1" | bemenu "${opts[@]}"
}

## Main ##


[[ -s $optsfile ]] && source "$optsfile"

num=$(apropos "$1" | wc -l)

case "$num" in
  0) result=$(get_selection .) ;;
  1) result=$1 ;;
  *) result=$(get_selection "$1") ;;
esac

[[ ! $result ]] && exit 0

if [[ ! $(apropos ${result%\(*}) ]]; then
  thingmenu -g  160x120 -x \
    "Posix" "exec browse '\!posix $1'" \
    "Mankier" "exec browse '\!mankier $1'" \
    "Man7" "exec browse '\!man7 $1'" \
    "Man" "exec browse '\!man $1'" 
else  
  result="${result%\)*}"
  handle_result "${result#\(*}" "${result%\(*}"
fi
