#!/usr/bin/env bash
## Find manuals

readonly optsfile="$XDG_CONFIG_HOME"/dmenu/bemenucolors

handle_result() {
   local width
   #Coloration, and match width
   width=$(tput cols)
   [[ $width -gt $MANWIDTH ]] && \
   exec env LESS=-RX \
   MANWIDTH="$width" \
   LESS_TERMCAP_mb=$'\E[01;31m' \
   LESS_TERMCAP_md=$'\E[01;38;5;74m' \
   LESS_TERMCAP_me=$'\E[0m' \
   LESS_TERMCAP_se=$'\E[0m' \
   LESS_TERMCAP_so=$'\E[38;5;246m' \
   LESS_TERMCAP_ue=$'\E[0m' \
   LESS_TERMCAP_us=$'\E[04;38;5;146m' \
   st -t float -e man "$1" "$2"
}

unchunk() {
    # Entries come here looking like fprintf, vfprintf(8) - foo bar baz
    # We need printed as fprintf(8) - foo bar baz
    #                    vfprintf(8) - foo bar baz
    while read -r line; do
        # Read in man # and desc
        last="${line##*\ -\ }"
        num="$(grep -o "(.*)" <<< "$line")"
        line="$(sed 's/(.*)//p' <<< "$line")"
        # Read in each chunk
        IFS=', ' read -ra TMP <<< "${line%%-\ *}"
        for i in "${TMP[@]}"; do
            printf '%s%s|- %s\n' "$i" "$num" "$last"
        done
    done
}

append() {
    while read -r line; do
        printf "$line\n"
    done
    printf '%s\n%s\n%s\n' "!g $1" "!die $1" "!man7 $1"
}


## Main ##

[[ -s $optsfile ]] && source "$optsfile"
opts+=(-l 10 -p "Select manual")

result="$(whatis "$1" || "$(apropos . | bemenu "${opts[@]}")")"

# Check for ambiguity
if [[ "$(unchunk <<< "$result" | wc -l)" -gt 1 ]]; then
    result=$(printf '%s\n' "$result" | unchunk | append "$1" | column -s '|' -t | bemenu "${opts[@]}")
fi

# If a bang, send it to browser
[[ $result == !* ]] && exec browse "https://duckduckgo.com?q=$result" 

# Send off to handler
[[ $result ]] && handle_result "${result//[a-zA-Z\(\)-_]/}" "${result%\(*}"
