#!/usr/bin/env bash

readonly confdir=${XDG_CONFIG_HOME:-$HOME/local/cfg}
readonly optsfile=$confdir/dmenu/bemenucolors
readonly termcmd="st -t float -e man"

handle_result() {
   local width
   # Coloration, and match width
   width=$(tput cols)
   [[ $width -gt $MANWIDTH ]] && width="$MANWIDTH"
   exec env LESS=-RX \
   MANWIDTH="$width" \
   LESS_TERMCAP_mb=$'\E[01;31m' \
   LESS_TERMCAP_md=$'\E[01;38;5;74m' \
   LESS_TERMCAP_me=$'\E[0m' \
   LESS_TERMCAP_se=$'\E[0m' \
   LESS_TERMCAP_so=$'\E[38;5;246m' \
   LESS_TERMCAP_ue=$'\E[0m' \
   LESS_TERMCAP_us=$'\E[04;38;5;146m' \
   $termcmd $1
}

get_selection() {
   apropos . | bemenu -l 10 "${opts[@]}" -p "Manual"
}

## Main ##
# Configuration
# https://github.com/halfwit/dotfiles/blob/master/.config/dmenu/font

if [[ -s $confdir/dmenu/font ]]; then
  read -r font < "$confdir"/dmenu/font
  opts+=(-fn "$font")
fi

if [[ -s $optsfile ]]; then
  source "$optsfile"
fi

[[ ! $1 ]] && result="$(get_selection)" || result=$1
result="${${result##\(*}%%\)} ${result%% *}"

if ! grep "$1" <<< $(apropos .); then
  exec vimb-run "\!posix $1"
fi


if [[ "$result" ]]; then
  handle_result "$result"
fi
