#!/usr/bin/env bash

readonly optsfile="$XDG_CONFIG_HOME"/dmenu/bemenucolors
readonly termcmd="st -t float -e man"

handle_result() {
   local width
   # Coloration, and match width
   width=$(tput cols)
   [[ $width -gt $MANWIDTH ]] && width="$MANWIDTH"
   exec env LESS=-RX \
   MANWIDTH="$width" \
   LESS_TERMCAP_mb=$'\E[01;31m' \
   LESS_TERMCAP_md=$'\E[01;38;5;74m' \
   LESS_TERMCAP_me=$'\E[0m' \
   LESS_TERMCAP_se=$'\E[0m' \
   LESS_TERMCAP_so=$'\E[38;5;246m' \
   LESS_TERMCAP_ue=$'\E[0m' \
   LESS_TERMCAP_us=$'\E[04;38;5;146m' \
   $termcmd $1
}

get_selection() {
  opts+=( -l 10 -p "Manual: " )
   apropos . | bemenu "${opts[@]}"
}

## Main ##
# Configuration
# https://github.com/halfwit/dotfiles/blob/master/.config/dmenu/font

[[ -s $optsfile ]] && source "$optsfile"

[[ ! $1 ]] && result="$(get_selection)" || result=$1
result="${${result##\(*}%%\)} ${result%% *}"

if ! grep "$1" <<< $(apropos .); then
  thingmenu -g  160x120 -x \
    "Posix" "exec vimb-run '\!posix $1'" \
    "Mankier" "exec vimb-run '\!mankier $1'" \
    "Man7" "exec vimb-run '\!man7 $1'" \
    "Man" "exec vimb-run '\!man $1'" 
fi


if [[ "$result" ]]; then
  handle_result "$result"
fi
