#!/bin/bash
## use last for last result
## use clip to send to clip

declare -a results

readonly histfile="/tmp/mathhist"

[[ -e $histfile ]] || touch "$histfile"

# Read in history
while read -r item; do
    results+=($item)
done < "$histfile"

# Sanitize input
if [[ $1 ]]; then
    [[ ${1[0]} =~ [0-9] ]] || inp="${results[-1]}$1"
    inp="${inp//\ /}"
else
    inp="$(printf '%s\n' "${results[@]}" | tac | dmenu -p "eval | clip: ")"
fi

# Break this out of the while loop.
while :; do
    if [[ "${results[@]}" =~ "$inp" ]]; then
        xcmenu -ic <<< "$inp"
        break
    fi
 
    invar=$(bc -l <<< "$inp" | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
   
    # If result matches entry 
    if [[ $invar ]]; then
        results+=($invar)
        inp="$(printf '%s\n' "${results[@]}" | tac | dmenu -p "eval | clip: ")"
        
        [[ ${inp[0]} =~ [0-9] ]] || inp="${results[-1]}$inp"
        
        inp="${inp//\ /}"
    else
        break
    fi

done

printf '%s\n' "${results[@]}" > "$histfile"
