#!/usr/bin/env bash
## load and play all music, turn on shuffle
## Will either accept a string as band filter, or play all playlists

if ! pgrep mpd; then
  mpd &
fi

opts=(-i)

case "$1" in
  Radio*|?*) opts+=($1)       ;;
  *)         opts+=(-v Radio) ;;
esac

mpc clear
mpc lsplaylist | grep "${opts[@]}" | while read -r item; do 
  mpc load "$item"
done
mpc random on
mpc play
