#!/usr/bin/env bash
# Create menu based on URLs and titles.
# https://github.com/Earnestly/dotfiles/blob/master/local/bin/bemenu-loader



get_selection() {
    bemenu-loader "$XDG_DATA_HOME/mpv/$1"
}

# Main
result=$(get_selection "$1")

[[ ! $result ]] && exit 0

mpv "$result"
