#!/usr/bin/env bash
# Front end for notes.


readonly optsfile=$XDG_CONFIG_HOME/dmenu/bemenucolors

create_menu() {
  cd $notedir
  for i in *; do 
    if [[ -s $i ]]; then 
      printf '%s\n' "$i"
    else 
      rm "$i"
    fi
  done
}

menu() {
  opts+=(-p "Select or create a new note: " -l 10)
  create_menu | bemenu "${opts[@]}"
}

## Main

# Theme for bemenu
[[ -s $optsfile ]] && source "$optsfile"


notedir=$XDG_CACHE_HOME/notes
result=$(menu)

[[ ! $result ]] && exit 
[[ ! -e $notedir/$result ]] && touch "$notedir/$result"

exec st -t NVIM -e /usr/bin/nvim "$notedir/$result"
