#!/usr/bin/env bash
# Front end for notes.

create_menu() {
  cd $notedir
  for i in *; do 
    if [[ -s $i ]]; then 
      printf '%s\n' "$i"
    else 
      rm "$i"
    fi
  done
}

menu() {
  create_menu | dmenu -p "Select note: "
}

## Main

# Theme for dmenu
[[ -s $optsfile ]] && source "$optsfile"


notedir=$XDG_CACHE_HOME/notes
result=$(menu)

[[ ! $result ]] && exit 
notify-send  "$(cat $notedir/$result)"
