#!/usr/bin/env bash

readonly optsfile="$XDG_CONFIG_HOME"/dmenu/bemenucolors

selection() {
  opts+=(-l 10 -p Upload)
  find ~/ -type f | bemenu "${opts[@]}" 
}

if [[ $1 ]]; then
  result="$1"
else
  [[ -s $optsfile ]] && source "$optsfile"
  result=$(selection)
fi

pbpst -Sf $result | xcmenu -ic #|| curl -sT- https://p.iotek.org < $result | xcmenu -ic
