#!/usr/bin/env bash

# Database of bookmarks for quick linking
# Use namespacing in the title (dead simple, yay!!)
readonly optsfile=$XDG_CONFIG_HOME/dmenu/dmenucolors

get_selection() {
  (cd "$HOME/media/pictures"
  find -type f -printf "IMG:$HOME/media/pictures/%f\t%f\n" )

}

[[ -s $optsfile ]] && source "$optsfile"

opts+=( -l 10 -p "Select photo" )
result=$(get_selection | dmenu "${opts[@]}" )

result=$(exiftool "$HOME/media/pictures/$result" | awk '/Comment/ { print $NF }')
result="${result//\"/}"

[[ $result ]] && exec xcmenu -ic "$result"
