#!/bin/sh

handle() {
	while read -r have inp _; do
		case "$have" in
			\[-\]*) st -e sudo xbps-install -Sy "$inp"  ;;
    		\[*\]*) st -e varless "`xbps-query "$inp"`" ;;
		esac
	done
}
xbps-query -Rs "$1" | dmenu -p "Select package: " | handle