#!/bin/sh

# We only care about the first two words in the string
handle() {
	while read -r installed name _; do
		case "$installed" in
			\[-\]*) st -e sudo xbps-install -Sy "$name"   ;;
			\[*\]*) st -e varless "$(xbps-query "$name")" ;;
		esac
	done
}

## Main pipeline
xbps-query -Rs "$1" | dmenu -p "Select package: " | handle