#!/bin/bash

. "$XDG_CONFIG_HOME"/dmenu/bemenucolors

result="$(xbps-query -Rs "$1" | bemenu "${opts[@]}")"
result="$(awk '{print $2}' <<< "$result")"

[[ $result ]] || exit 0
if xbps-query "$result"; then
	st -e varless "$(xbps-query "$result")" 	
else
	st -e sudo xbps-install -Sy "$result"
fi