#!/bin/bash

# Update RSS feed of "read later"
source "$XDG_CONFIG_HOME"/dmenu/dmenucolors

opts+=(-p "Select url" -l 10)
URL=$(xcmenu --list | dmenu "${opts[@]}")

# Make sure we have something
TITLE=$(curl $URL -so - | grep -iPo '(?<=<title>)(.*)(?=</title>)' || echo "" | dmenu "${opts[@]}" -p "Enter title")

printf '%s\n' "$URL" > "$XDG_CACHE_HOME"/readlater/"$TITLE"
