#!/usr/bin/env bash

# Requires dmenu, ag

get_selection() {
    ag -t --nofilename "$1" | dmenu -p "Select quote: "
}

# Main

# Configuration

result=$(get_selection "$1")

# Verify a selection was made
if [[ $result ]]; then
  xcmenu -ic <<< "$result" 
fi
