#!/usr/bin/env bash

# Requires dmenu, ag

readonly optsfile=$XDG_CONFIG_HOME/dmenu/dmenucolors

get_selection() {
    opts+=( -l 10 -p "Select quote: " )
    ag -t --nofilename "$1" | dmenu "${opts[@]}"
}

# Main

# Configuration

[[ -s $optsfile ]] && source "$optsfile"

result=$(get_selection "$1")

# Verify a selection was made
if [[ $result ]]; then
  xcmenu -ic <<< "$result" 
fi
