#!/usr/bin/env bash

# Gmusicproxy host IP
readonly host=192.168.0.103

# Gmusicproxy default port
readonly port=9999

readonly numtracks=100
readonly url=http://$host:$port

receive_playlist() {
    curl -s "$url/$1?num_tracks=$numtracks" > "${XDG_CONFIG_HOME:-$HOME/.config}"/mpd/playlists/now_playing.m3u 
}

mpc clear
mpc rm now_playing
case $1 in
    ifl) receive_playlist "get_ifl_station" ;;
    *) receive_playlist "get_new_station_by_search?type=artist&artist=${1// /+}&exact=no" ;;
esac

mpc load now_playing
mpc play

# cleaning up playlist
rm "$XDG_CONFIG_HOME"/mpd/playlists/now_playing.m3u
mpc save now_playing
