#!/usr/bin/env bash

# Gmusicproxy host IP
readonly host=192.168.0.103

# Gmusicproxy default port
readonly port=9999

readonly numtracks=100
readonly url=http://$host:$port

receive_playlist() {
    curl -s "$url/$1?num_tracks=$numtracks" > "$XDG_CONFIG_HOME/mpd/playlists/$2.m3u" 
}

mpc clear
case $1 in
    ifl) receive_playlist "get_ifl_station" "$1" ;;
    *) receive_playlist "get_new_station_by_search?type=artist&artist=${1// /%20}&exact=no" "$1" ;;
esac
mpc load "$1"
mpc play
