#!/bin/sh

RL="$XDG_CACHE_HOME/read later"

# read items from read later list
result() {
  while {
    read -r title 
    read -r url
  } do
    printf '%s\n' "$title"
  done < "$RL" | dmenu -l 10 
} 

tmp=$(mktemp)

RESULT="$(result)"
test -z $RESULT && exit 0

URL=$(grep -A 1 -- "$RESULT" "$RL" | tail -n 1)
grep -v -e "$RESULT" -e "$URL" "$RL" > "$tmp"
mv "$tmp" "$RL"
exec plumber "$URL"
