#!/usr/bin/env bash

RL="$XDG_CACHE_HOME/readlater"

source $XDG_CONFIG_HOME/dmenu/dmenucolors
opts+=(-l 10 -p "Read next")
# read items from read later list

RESULT=$(find "$RL" -type f ! -name .stfolder -printf "%f\n" | dmenu "${opts[@]}")
test -z "$RESULT" && exit 0

plumber "$(cat "$RL/$RESULT")"
