#!/usr/bin/env bash

## Reddit image-enabled search utility
## Requires 
#  https://github.com/Cloudef/dmenu-pango-imlib
#  https://github.com/keenerd/jshon

tmp=$(mktemp -d /tmp/reddit.XXXX)

fetch() {
    curl -s -X GET -L "https://www.reddit.com/r/${1//\ /%20}/new/.json?count=50" -A "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MOB3OD)" | jshon -e data -e children -a -e data -e title -upe permalink -upe thumbnail -upe link_flair_text -u 
}

build_dirs() {
    local title url thumbnail flair
    while {
        read -r title
        read -r url
        read -r thumbnail
        read -r flair
    } do
        title="${title//\/}"
        curl -s "$thumbnail" -o "$tmp/$title.image" &
        printf '%s\n' "$url" > "$tmp/$title.url"
        if [[ $flair ]]; then
            printf 'IMG:%b\t%s\t- %s\n' "$tmp/$title.image" "[$flair]" "$title" 
        else
            printf 'IMG:%b\t%s\n' "$tmp/$title.image" "$title"
        fi
    done
}

handle_selection() {
    local url
    while read -r selection; do
        read -r url < "$tmp/${selection##*-\ }.url"
        [[ $url ]] && st -t news -e browse "https://www.reddit.com$url" &
    done
    rm -rf "$tmp"
}


## Main 
fetch "$1" | build_dirs | dmenu -p "Select post: " -is 140x140 | handle_selection
