#!/bin/bash

## Dmenu based frontend to read RSS directory
RSS=$XDG_CACHE_HOME/rss
declare all=false

select_site() {
    cd "$1"
    for i in *; do
        [[ "$i" != "url" ]] && printf '%s\n' "$i"
    done
}

update_count() {
	ls "$RSS" | while read -r title; do
		if ls "$RSS/$title"/\[new\]* &>/dev/null; then
			printf '%s\n' "$title"
		fi 
	done | wc -l | bc > "$RSS"/count
}

filter_read() {
	while read -r title; do
		if [[ $all == true ]]; then
			printf '%s\n' "$title"
		elif ls "$RSS/$title"/\[new\]* &>/dev/null; then
            printf '%s\n' "$title"
        fi
    done
	printf '%s\n%s\n' "view all" "quit"
}

mark_read() {
	cd "$RSS/$1"
	for i in *; do
		mv "$i" "${i/\[new\]\ /}"
	done
}

append() {
	while read -r entry; do
		printf '%s\n' "$entry"
	done
	printf '%s\n' "$1"
}

select_post() {
	local feed
	echo "$RSS/$1"
	while :; do
		update_count
		feed="$(ls -t -I url -I count "$RSS/$1" | append "clear posts" | dmenu -p "Select post: ")"
		[[ ! $feed ]] && break
		case "$feed" in
			clear\ posts) 	mark_read "$1"
							break ;;
			quit)        	break ;;
		esac
    	read -r url < "$RSS/$1/$feed"
    	mv "$RSS/$1/$feed" "$RSS/$1/${feed/\[new\]\ /}"
    	plumber "$url" & 
	done
}

# each count check 
select_feed() {
	local feed
	while :; do
		update_count
		feed="$(ls "$RSS" | filter_read | dmenu -p "Select sub: ")"
		[[ ! $feed ]] && break
		case "$feed" in
			view\ all) 	all=true				;;
			quit)		break 					;;
			*)			all=false
						select_post "$feed" 	;;
		esac
	done
}

select_feed
