#!/bin/bash

## Dmenu based frontend to read RSS directory
RSS=$XDG_CACHE_HOME/rss
source "$XDG_CONFIG_HOME"/dmenu/dmenucolors

select_site() {
    cd "$1"
    for i in *; do
        [[ "$i" != "url" ]] && printf '%s\n' "$i"
    done
}

filter_read() {
    while read -r title; do
        if ls "$RSS/$title"/\[new\]* &>/dev/null; then
            printf '%s\n' "$title"
        fi
    done
    printf '%s\n%s\n' "view all" "quit"
}

append() {
    while read -r entry; do
        printf '%s\n' "$entry"
    done
    printf '%s\n' "$1"
}

handle_result() {
    read -r selection
    if [[ $selection == "mark all as read" ]]; then
        cd "$RSS/$1"
        for i in *; do
            mv "$i" "${i/\[new\]\ /}"
        done
        exit 0 
    fi
    if [[ $selection == "quit" ]]; then
        exit 0
    fi

    read -r url < "$RSS/$1/$selection"
    mv "$RSS/$1/$selection" "$RSS/$1/${selection/\[new\]\ /}"
    plumber "$url" & 
}

opts+=(-p "Select sub" -l 10)
feed=$(select_site "$RSS" | filter_read | dmenu "${opts[@]}")

if [[ $feed == "view all" ]]; then
    feed=$(select_site "$RSS" | append "quit" | dmenu "${opts[@]}") 
fi

if [[ $feed == "quit" || ! $feed ]]; then
    exit 0
fi

opts+=(-p "Select feed")
select_site "$RSS/$feed" | tac | append "mark all as read" | append "quit" |  dmenu "${opts[@]}" | handle_result "$feed"

sleep .1
exec "$XDG_DATA_HOME"/dsearch/rss
