#!/usr/bin/env bash

# Tool to save arbitrary things from the current clip to various locations
readonly optsdir=$XDG_CONFIG_HOME/dmenu/bemenucolors

[[ $optsdir ]] && source "$optsdir"

case $(curl -sI "$@" | grep -i content-type) in
  *pdf*|*epub*|*djvu*)
    # Add image selection
    cover="https://ptpb.pw/REYs.png"
    result=$(printf '%s' | bemenu "${opts[@]}" -p "Save document")
    bookkeep "$result" mk -t pdf -e nvim -c "$cover"
    curl -s "$1" > media/docs/pdf/"$result"
    break ;;
  *image*)
    result=$(printf '%s' | bemenu "${opts[@]}" -p "Save picture")
    curl -s "$1" >  "$HOME/media/pictures/$result"
    exiftool -overwrite_original -Comment=\"$1\" "$HOME/media/pictures/$result"
    break ;;
  *video*)
    exec "$XDG_DATA_HOME/dsearch/savepl" "$1" 
    break ;;
  *)
    result=$(printf '%s' | bemenu "${opts[@]}" -p "Save bookmark") 
    [[ $result ]] && printf '%s' "$1" > "$XDG_DATA_HOME/bookmark/$result"
    break ;;
esac
