#!/usr/bin/env bash

# Tool to save arbitrary things from the current clip to various locations

readonly optsdir=$XDG_CONFIG_HOME/dmenu/bemenucolors

[[ $optsdir ]] && source "$optsdir"

[[ $1 ]] && read -r input <<< "$1" || input=$(xcmenuctrl -u)

name() {
  opts+=(-l 1 -p "Save $1 as:")
  printf '\n' | bemenu "${opts[@]}" 
}

document() {
  local result cover
  read -r result
  cover="https://ptpb.pw/REYs.png"
  [[ $result ]] && st - e bookkeep "$result" mk -t "$1" -e nvim -c "$cover"
  if [[ -s $XDG_DATA_HOME/librarian/bin/$result ]]; then
    curl -s "$2" > media/docs/"$1/$result"
  fi
}

image() {
  local result input
  read -r result
  [[ $result ]] && curl -s "$1" >  "$HOME/media/pictures/$result"
  if [[ -s "$HOME/media/pictures/$result" ]]; then
    exiftool -overwrite_original -Comment=\""$1"\"  "$HOME/media/pictures/$result"
  fi
}

note() {
  local result
  read -r result
  curl -s "$1" > "$XDG_CACHE_HOME"/notes/"$result"
}

[[ $input ]] && case $(curl -sI "$input" | grep -i content-type) in
  *text/plain*) name "note"     | note       "$input" ;;
  *image*)      name "picture"  | image      "$input" ;;
  *djvu*)       name "document" | doc "djvu" "$input" ;;
  *epub*)       name "document" | doc "epub" "$input" ;;
  *pdf*)        name "document" | doc "pdf"  "$input" ;;
  *video*) exec "$XDG_DATA_HOME/youtube/savepl" "$input" ;;
  *)
    items=( "git - " "error - " "keyboards - " "linux - "
            "main - " "programming - " "electronics - " )
    opts+=( -l 10 -p "Save bookmark" )
    result=$(printf '%s\n' "${items[@]}" | bemenu "${opts[@]}") 
    [[ $result ]] && printf '%s' "$input" > "$XDG_DATA_HOME/bookmark/$result"
    ;;
esac
