#!/usr/bin/env bash

# Tool to save arbitrary things from the current clip to various locations

readonly optsdir=$XDG_CONFIG_HOME/dmenu/dmenucolors

[[ $optsdir ]] && source "$optsdir"


name() {
  opts+=(-l 1 -p "Save $1 as:")
  printf '\n' | dmenu "${opts[@]}" 
}

doc() {
  local result cover
  read -r result
  cover="https://ptpb.pw/REYs.png"
  [[ $result ]] && st -t float -e /home/halfwit/local/bin/bookkeep mk "$result" -t "$1" -e nvim -c "$cover"
  if [[ -s $XDG_DATA_HOME/librarian/bin/$result ]]; then
    curl -s "$2" > media/docs/"$result.$1"
  fi
}

image() {
  local result input
  read -r result
  [[ $result ]] && curl -s "$1" >  "$HOME/media/pictures/$result"
  if [[ -s "$HOME/media/pictures/$result" ]]; then
    exiftool -overwrite_original -Comment="$1"  "$HOME/media/pictures/$result"
  fi
}

note() {
  local result
  read -r result
  curl -s "$1" > "$XDG_CACHE_HOME"/notes/"$result"
}

save_feed() {
  opts+=(-p "Save feed as:")
  title="$(echo "" | dmenu "${opts[@]}")"
  mkdir "$XDG_CACHE_HOME/rss/$title"
  echo "$1" > "$XDG_CACHE_HOME/rss/$title"
}

lsw | while read -r w; do
  case $(wname "$w") in
    *browse*) sed -n -e 's/_SURF_URI(STRING) = "//p' <<< "$(xprop -id "$w")" | tr -d '"' | xcmenu -ic ;;
  esac
done

[[ $1 ]] && input="$1" || input=$(xcmenuctrl -u)

if grep "github" <<< "$input"; then
  cd $HOME/code
  st -t float -g 45x4+20+20 -e git clone "$input"
  cd "${input##*/}"
  st &
  exit 0
fi

[[ $input ]] && case $(curl -sI "$input" | grep -i content-type) in
  *text/plain*) name "note"     | note       "$input" ;;
  *image*)      name "picture"  | image      "$input" ;;
  *djvu*)       name "document" | doc "djvu" "$input" ;;
  *epub*)       name "document" | doc "epub" "$input" ;;
  *pdf*)        name "document" | doc "pdf"  "$input" ;;
  *video*) exec "$XDG_DATA_HOME/youtube/savepl" "$input" ;;
  *application/atom*) save_feed "$input" ;;
  *application/rss*)  save_feed "$input" ;;
  *)
    items=( "git - " "error - " "keyboards - " "linux - "
            "main - " "programming - " "electronics - " )
    opts+=( -l 10 -p "Save bookmark" )
    result=$(printf '%s\n' "${items[@]}" | dmenu "${opts[@]}") 
    [[ $result ]] && printf '%s' "$input" > "$XDG_DATA_HOME/bookmark/$result"
    ;;
esac
