#!/usr/bin/env bash
## List current playlist
#  I generally have all of my music on the playlist
#  Adjust for your own needs

readonly optsdir=$XDG_CONFIG_HOME/dmenu/bemenucolors

load() {
	local i=0 result
	result=$(mpc playlist | while read -r title; do
		printf '%s %s\n' "$((++i))" "$title"
	done | bemenu "${opts[@]}")
}
## Main

[[ $optsdir ]] && source "$optsdir"
opts+=(-p "Select song: " -l 10)

if [[ $1 ]]; then
	result=$1
else
	result="$(load)"
fi	

[[ $result ]] || exit 0

# If we don't have the song at all, grab it from youtube
if ! mpc playlist | grep "$result"; then
	youtube-dl "ytsearch:$result" --get-url -f 140 | mpc insert
	mpc next
else
	mpc play "${result%%\ *}"
fi
