#!/usr/bin/env bash

# Gmusic host IP
readonly host=192.168.0.103

# Gmusicproxy default port
readonly port=9999
readonly optsdir=$XDG_CONFIG_HOME/dmenu/bemenucolors
readonly url=http://$host:$port

add_song() {     
    mpc insert "$url/get_by_search?type=song&artist=${1// /%20}&title=${2// /%20}&exact=no"
    mpc next
}

load() {
  local i=0
  mpc playlist | while read -r title; do
    printf '%s %s\n' "$((++i))" "$title"
  done
}

if [[ $1 ]]; then 
  add_song "${1%\ -*}" "${1#*-\ }"
  exit 0
fi
# Grab opts, split around '-'
[[ $optsdir ]] && source "$optsdir"

opts+=(-p "Select song: " -l 10 ) 

result=$(load | bemenu "${opts[@]}")

mpc play "${result%%\ *}"
