#!/usr/bin/env bash
## List current playlist

readonly optsdir=$XDG_CONFIG_HOME/dmenu/dmenucolors

load() {
  local i=0 result
  result=$(mpc playlist | while read -r title; do
    printf '%s %s\n' "$((++i))" "$title"
  done | dmenu "${opts[@]}")
  [[ ! $result ]] && exit 1
  mpc play "${result%%\ *}"
}

querysong() {
  echo "Not found!"
}

findsong() {
  local result dir num name
  result="$(grep -Fsrni "$1" ~/local/cfg/mpd/playlists)"
  if [[ $(wc -l <<< "$result") -gt 1 ]]; then
    result="$(dmenu "${opts[@]}" -l 10 <<< "$result")"
  fi
  [[ ! $result ]] && exit 1
  while IFS=":" read -r dir num name; do
    dir="${dir/.m3u/}" 
    mpc clear
    mpc load "${dir##*\/}"
    mpc play "$(( num / 2 ))"
  break
  done <<< "$result"
}

## Main

[[ $optsdir ]] && source "$optsdir"
opts+=(-p "Select song: " -l 10)

if [[ $1 ]]; then
  grep -Fsrni "$1" ~/local/cfg/mpd/playlists && findsong "$1" || querysong "$1"
else 
  load
fi
