#!/usr/bin/env bash
# Handler to push window to top of stack

lsw -a | while read -r id; do
  if xwininfo "$id" | grep -a "$1"; then
    mapw -m "$id"
    grp 2 "$id"
  elif xwininfo "$id" | grep -a "browse - "; then
    mapw -u "$id"
  fi
done
