#!/usr/bin/env bash
# Write/remove a task to do later.

readonly optsfile=$XDG_CONFIG_HOME/dmenu/bemenucolors

menu() {
  opts+=( -p "Select or create new task" -l 10)
  find "$XDG_CACHE_HOME"/todo -not -path '*/\.*' -type f -printf "%f\n" | bemenu "${opts[@]}"
}

## Main

[[ -s $optsfile ]] && source "$optsfile"

result=$(menu)
[[ ! $result ]] && exit 

touch "$XDG_CACHE_HOME/todo/$result"
exec ~/local/share/todo/singletask "$result"
