#!/usr/bin/env bash
# Create menu based on URLs and titles.

readonly datadir=${XDG_DATA_HOME:-$HOME/local/share}
readonly optsfile="$XDG_CONFIG_HOME"/dmenu/dmenucolors

# Main

[[ -s $optsfile ]] && source "$optsfile"

#[[ ! $result ]] && exit 0

main() {
n=$(echo '{ "command": ["get_property", "playlist-count"] }' | socat - /tmp/mpvsock | jshon -e data)

for (( i = 0; i < n; i++ )); do
  URL=$(echo '{ "command": ["get_property_string", "playlist/'$i'/filename"] }' | socat - /tmp/mpvsock | jshon -e data -u)
  case "$URL" in
    ytdl://*) URL="www.youtube.com/watch?v=${URL#*\/\/}" ;;
  esac
  
  [[ $URL ]] && printf '%s %s\n' "$i" "$(youtube-dl -e "$URL")" &
done

}

opts+=( -l 10 -p "Select video")
result=$(main | dmenu "${opts[@]}")

echo '{ "command": ["set_property", "playlist-pos", '${result%%\ *}'] }' | socat - /tmp/mpvsock, 
