#!/usr/bin/env bash

tmp=$(mktemp -d /tmp/wk.XXXX)
URL="https://en.wikipedia.org/w/api.php?action=opensearch&search=$(echo $1 | sed 's/ /_/')&namespace=0&format=json"

build() {
		count=$(jshon -F $tmp/json -e 1 -a -u | wc -l)
		for i in `seq 1 $count`; do
				jshon -F $tmp/json -e 1 -e $i -uppe 2 -e $i -uppe 3 -e $i -u
		done
}

chunk() {
		while {
				read -r title
				read -r desc
				read -r url
		} do
				echo "$desc" > "$tmp/$title"
				echo "$url" >> "$tmp/$title"
				printf '%s\n' "$title"
		done
}

curl -s "$URL" -o "$tmp"/json
count=$(jshon -F $tmp/json -e 1 -a -u | wc -l)

# Check if we need to disambiguate
if [[ $count -gt 1 ]]; then
		result="$(build | chunk | dmenu -p "Select disambiguation: ")"
else
		result="$(jshon -F $tmp/json -e 1 -a -uppe 2 -a -uppe 3 -a -u | chunk)"
fi

xurls < "$tmp/$result" | xcmenu -ic
notify-send "$(cat "$tmp/$result")"
