#!/usr/bin/env bash
# Youtube search handler

readonly optsfile="$XDG_CONFIG_HOME"/dmenu/dmenucolors
readonly images="$(mktemp -d /tmp/yt.XXXX)"
readonly requests=5

fetch_json() {
  local key
  read -r key < "$XDG_DATA_HOME/youtube/key"
  curl -s "https://www.googleapis.com/youtube/v3/search?q=${1// /%20}&type=video&part=snippet&maxResults=$requests&key=$key"
}

parse_json() {
	# we need to pull out the URL in this same call, to stdout.
  jshon -CQ -e items -a -e snippet -e title -uppe id -e videoId -uppe snippet -e thumbnails -e high -e url -u 
}

curl_images() {
  local name url
  
  while {
    read -r name
    read -r _
    read -r url 
  } do
    curl -s "$url" -o "$images/$name" $ 
    printf 'IMG:%q\t%s\n' "$images/$name" "$name"
  done
  wait
}

# Main
## Handle instance
[[ "$1" == save ]] && exec "$XDG_DATA_HOME"/youtube/savepl

[[ -s $optsfile ]] && source "$optsfile"
opts+=( -l "$request" -p "Select video" )

fetch_json "$@" | parse_json | curl_images | dmenu "${opts[@]}"
