#!/bin/sh
yt() {
	play "$1" &
	exit 1
}

to() {
	browse "$1" &
	exit 1
}

asci() {
	st -e asciinema play "$1" &
	exit 1
}

view() {
	tmp=$(mktemp)
	curl -Lsk "$1" -o "$tmp"
	imv "$tmp" &
	exit 1
}

case "$@" in
	*bell-labs.com*) 	url="$(echo "$1" | sed 's/.\+com//')"
				to "http://9p.io$url" ;;
	*youtube.com/watch*)	yt "$@" ;;
	*youtube.com/embed*)    yt "$@" ;;
	*youtu.be*)		yt "$@" ;;
	https://go.twitch.tv/videos*) yt "$@" ;;
	*youtube.com/v/*)	yt "$@" ;;
	ytdl*)			yt "$@" ;;
	*youtube.com/play*)	yt "$@" ;;
	*youtube.com/channel*)	/usr/local/share/dsearch/yt "$@" 
					exit 1;;
	*youtube.com/user/*) /usr/local/share/dsearch/yt "$@"
					exit 1;;
	*futurism.com/videos*) yt "$@" ;;
	*.mp4|*.mp3)	yt "$@" ;;
	*bandcamp*)     yt "$@" ;;
	*soundcloud*)   yt "$@" ;;
	*bpaste.net/show*) plumber "$(echo "$1" | sed 's/show/raw/')" 
					exit 1 ;;
	*gfycat.com*)	yt "$@" ;; 
	*http://music*) yt "$@" ;;
	*webm)			yt "$@" ;;
	*mkv)			yt "$@" ;;
	*gif)			yt "$@" ;;	
	*gifv)			yt "$@" ;;
	*png)			view "$@" ;;
	https://pic.twitter.com*) URL="$(curl -sIL "$@" | sed -n 's/^location: //pI')"
					plumber "$URL" &
					exit 1 ;;
	https://t.co*)  URL="$(curl -sIL "$@" | sed -n 's/^Location: //pI')"
					plumber "$URL" &
					exit 1 ;;
	gopher://*)		st -c gopher -e cgo "$1" &
					exit 1 ;;
	*asciinema*)	asci "$(echo "$1" | sed 's|/t||')" 	;;
	*ptpb.pw/t/*)   asci "$(echo "$1" | sed 's|/t||')"  ;;
	ISBN*)			URL=`echo $@ | awk '{print $2}'`
				to "https://duckduckgo.com?q=!a%20$URL" ;;
		
	*ptpb.pw/*/*) 		URL=`echo $@ | cut -b 1-20`			
				plumber "$URL" &
				exit 1 ;; 
	ftp://*)		to "$@" ;;
	*teknik*)   view "$@" ;;
		
esac

exit 0
