#!/bin/sh

getname() {
  cd "$XDG_CONFIG_HOME"/x11/windows
  for i in ./*; do
    watom "$1" WM_NAME | grep -io "$i" && break
    watom "$1" _NET_WM_NAME | grep -io "$i" && break
  done
}

# See if already exists
case "`getname $1`" in
  mpv*)        grp=1 ;;
  surf*)       wtf "$1" && grp=2 ;;
  Chromium*)   wtf "$1" && grp=2 ;;
  Firefox*)    wtf "$1" && grp=2 ;;
  browse*)     wtf "$1" && grp=2 ;;
  NVIM*)       wtf "$1" && grp=3 ;;
  mutt*|news*) wtf "$1" && grp=4 ;;
  irc*)        wtf "$1" && grp=5 ;;
  *docs*)      wtf "$1" && grp=6 ;;
  zathura*)    wtf "$1" && grp=6 ;;
esac

chwso -r "$1"

if test -n $grp; then
  grp "$grp" "$1"
  "$XDG_DATA_HOME"/x11/groupsbar
fi
