#!/usr/bin/env bash

if [[ ! -p /tmp/panel ]]; then
  mkfifo /tmp/panel
fi
while true; do
  if read info </tmp/panel; then
    printf '%s\n' "$info" 
  fi
done | lemonbar -F '#bcbcbc' -b -d -f "DejaVu Mono:size=10" 
