#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# toggle the fullscreen state of a window
# depends on: focus.sh

FSFILE=${FSFILE:-/tmp/fwin}

if test -f $FSFILE; then
    rm -f $FSFILE
    "$XDG_DATA_HOME"/x11/wshuf
else
    echo "$1" >  $FSFILE
    . "$XDG_CONFIG_HOME"/x11/size
    wtp "$gaps" "$gaps" "$fulw" "$fulh" "$1"
    chwso -r "$1"
fi

wtf "$1"
