#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# toggle the fullscreen state of a window
# depends on: focus.sh

FSFILE=${FSFILE:-/tmp/fwin}
SIZE=$XDG_CONFIG_HOME/x11/size

if test -f $FSFILE; then
    cat $FSFILE | xargs -n 5 wtp
    rm -f $FSFILE
else
    wattr xywhi $1 > $FSFILE
    wtp $(sed -ne 's/gaps=//p' $SIZE) \
        $(sed -ne 's/gaps=//p' $SIZE) \
        $(sed -ne 's/fulw=//p' $SIZE) \
        $(sed -ne 's/fulh=//p' $SIZE) $1
    chwso -r "$1"
fi

wtf "$1"
