#!/usr/bin/env bash

# Number of groups
panels=6
declare -a item

for (( i = 1; i <= $panels; i++ )); do
  groups=$(lsgrp "$i")
  if [[ $groups != "" ]]; then
    if lsgrp "$i" | xargs wattr m; then
      item[$i]="◉"
    else
      item[$i]="◍"
    fi
  else
    item[$i]="◌"
  fi
  result+=${item["$i"]} 
done

printf '%s\n' "%{c}—${result[@]}—" > /tmp/panel
