#!/bin/sh
#
# Copyright (c) 2015 Greduan <me@greduan.com>, licensed under the WTFPL
# Adds group-like capabilities, sorta like those you find in CWM and such WMs


toggle() {
  # like lsw, for groups
  lsgrp $1 | while read -r id; do
    if wattr m "$id"; then
      mapw -t "$id"
    fi
  done
}

case "$1" in
  0x0*) grp "$2" "$1" ;;
  *) toggle "$1"      ;;
esac
