#!/usr/bin/env bash

while :; do
  current=""
  if mpc status | grep -q playing; then
    current="$(mpc current --format "%artist% - %title%")"
    [[ ${#current} -gt 80 ]] && current="${current:0:10}...${current:(-70)}"
  elif mpc status | grep -q paused; then
    current="[paused] "
  fi
  level=100
  read -r level < /sys/class/power_supply/BAT0/capacity
  if [ $level -lt 100 ]; then
    level="$level%"
  else
    level=""
  fi

  rss=$(find ~/local/cache/rss -name "\[new\]*" | wc -l)
  if [[ $rss != 0 ]]; then
  	rss="%{r}-$rss-"
  else
	rss=""
  fi

  printf '%s %s %s\n' "$level" "$rss" "%{r}$current "
  sleep 1
done | lemonbar -F '#bcbcbc' -d -b -f "DejaVu Mono:size=9.5" &
