#!/usr/bin/env bash

while :; do
  current=""
  if mpc status | grep -q playing; then
    current="$(mpc current --format "%artist% - %title% $(date -d@$(mpdtime) +%-M:%S)/%time%")"
    [[ ${#current} -gt 80 ]] && current="${current:0:10}...${current:(-70)}"
  elif mpc status | grep -q paused; then
    current="[paused] "
  fi
  level=100
  read -r level < /sys/class/power_supply/BAT0/capacity
  if [ $level -lt 20 ]; then
    level="- $level%"
  else
    level=""
  fi
  
  rss=$(find ~/local/cache/rss -name "\[new\]*" | wc -l)

  [ $rss -gt 0 ] && rss="%{r}-$rss-"
  
  printf ' %s %s %s %s\n' "$(date +'%H:%M')" "%{F#AF5F5F}$level%{F-}" "$rss" "%{r}$current "
  sleep 1
done | lemonbar -F '#bcbcbc' -d -b -f "DejaVu Mono:size=9.5" &
