#!/bin/sh
# Requires lsw https://github.com/wmutils
# Requires x11fs groups fork https://github.com/halfwit/x11fs

# directory of files that correlate to window names
WIN="$XDG_CONFIG_HOME"/x11/windows

getname() {
  cd $WIN
  for i in *; do
    wname "$1" | grep -io "$i" && break
  done
}

winsize() {
  while read -r id; do
    name=$(getname $id)
    test -f $WIN/$name && . $WIN/$name || . $WIN/default
  done
}

## Main ##
# window dimensions and gap
. "$XDG_CONFIG_HOME"/x11/size && [ ! $width ] && [ !$heigh ] && exit 1
lsw | winsize | binpack -x "$width" -y "$heigh" -g "$gaps" | xargs -n 5 wtp
