#!/bin/sh
# Requires https://github.com/wmutils

# directory of files that correlate to window names
WIN="$XDG_CONFIG_HOME"/x11/windows

getname() {
  cd $WIN
  for i in *; do
    watom "$1" WM_NAME | grep -io "$i" && break
  done
}

winsize() {
  while read -r id; do
    name=$(getname $id)
    test -f $WIN/$name && . $WIN/$name || . $WIN/default
  done
}

## Main ##
# window dimensions and gap
[ -f /tmp/fwin ] && exit 0

. "$XDG_CONFIG_HOME"/x11/size && [ ! $width ] && [ !$heigh ] && exit 1
lsw | winsize | binpack -x "$width" -y "$heigh" -g "$gaps" | xargs -n 5 wtp
