#!/usr/bin/env bash

groups() {
  "$XDG_CONFIG_HOME"/wmutils/groups -s "$1" "$2"
} 


case $(wname $1) in
  *mpv*)               groups "$1" 1 ;;
  *w3m*|*browse*)      groups "$1" 2 ;;
  *NVIM*)              groups "$1" 3 ;;
  *mutt*|*newsbeuter*) groups "$1" 4 ;;
  irc)                 groups "$1" 5 ;;
  *Zathura*)           groups "$1" 6 ;;
esac
