#!/usr/bin/env bash

groups() {
  "$XDG_CONFIG_HOME"/wmutils/groups -s "$1" "$2"
} 

wname=$(xwininfo -id "$1" | awk '/Window id:/{print $NF}')

case ${wname//\"/} in
  mpv|htop)                   groups "$1" 1 ;;
  w3m|*browse)                groups "$1" 2 ;;
  NVIM)                       groups "$1" 3 ;;
  mutt|newsbeuter)            groups "$1" 4 ;;
  zathura)                    groups "$1" 6 ;;
esac
