#!/usr/bin/env bash

# Go through files
WINDIR=${WINDIR:-/tmp/groups}
# Number of groups
panels=6

run_loop() {
  cd $WINDIR 
  local -a items
  local result
  for (( i = 1; i <= $panels; i++ )); do
    if grep "$i" active >/dev/null; then
      item[$i]="◉"
    elif grep "$i" inactive >/dev/null; then
      item[$i]="◍"
    else
      item[$i]="◌"
    fi
    result+=${item["$i"]}
  done
  printf '%s\n' "—${result[@]}—"
}

wendy -m 2 -f /tmp/groups/ -v | while read item; do
  case $item in
    *active)
      run_loop  ;;
    *inactive)  
      run_loop  ;;
    *cleanup)
      run_loop  ;;
  esac
done | lemonbar -d -b -f "DejaVu Sans" -g +$(( -60 + $(wattr w "$(lsw -r)") / 2)) &

while :; do
  level=100
  read -r level < /sys/class/power_supply/BAT0/capacity
  printf '%s %s %s\n' "$(date +'%b %d %H:%M')" "-" "$level%"
  sleep 60
done | lemonbar -d -b -f "DejaVu Mono" -g +4 &
