#!/usr/bin/env bash

# Go through files
WINDIR=${WINDIR:-/tmp/groups}

# Number of groups
panels=6

run_loop() {
  cd $WINDIR 
  local -a items
  local result
  for (( i = 1; i <= $panels; i++ )); do
    if grep "$i" active >/dev/null; then
      item[$i]="◉"
    elif grep "$i" inactive >/dev/null; then
      item[$i]="◍"
    else
      item[$i]="◌"
    fi
    result+=${item["$i"]}
  done
  printf '%s\n' "%{c}—${result[@]}—"
}

wendy -m 514 -f /tmp/groups/ -v | while read item; do
  case $item in
    *active)
      run_loop  ;;
    *inactive)  
      run_loop  ;;
    512*)
      run_loop  ;;
  esac
done | lemonbar -F '#444444' -d -b -f "DejaVu Sans Mono:size=12" &


while :; do
  current=""
  if mpc status | grep playing >/dev/null; then
    current="$(mpc current)"
  elif mpc status | grep paused >/dev/null; then
    current="[paused] "
  fi
  level=100
  read -r level < /sys/class/power_supply/BAT0/capacity
  printf ' %s - %s%s\n' "$(date +'%H:%M')" "$level%" "%{r}$current "
  if [[ $current ]]; then
    mpc idle player > /dev/null
  else 
    sleep 60
  fi
done |  lemonbar -F '#444444' -d -b -f "Inconsolatazi4 Regular:size=9.5" &
