#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# focus a window when it is created
# depends on: wew focus.sh

shuffle() {
  if ! xwininfo -id "$1" | grep dunst; then
    ~/local/cfg/wmutils/wshuf
    ~/local/cfg/wmutils/focus "$2"
  fi
}

wew | while IFS=: read ev wid; do
    case $ev in
        # occurs on mapping requests
        17)     ~/local/cfg/wmutils/groups -c "$wid"   
                shuffle "$wid" "next"                  ;;
        18)     shuffle "$wid" "next"                  ;;
        16|19)  shuffle "$wid" "$wid"                  ;;
    esac
done
