#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# focus a window when it is created
# depends on: wew focus.sh

shuffle() {
    ~/local/cfg/wmutils/wshuf
    ~/local/cfg/wmutils/focus "$2"
}

wew | while IFS=: read ev wid; do
  case $ev in
    16)         ~/local/cfg/wmutils/autotag "$wid" ;;
    17) ~/local/cfg/wmutils/groups -c "$wid"  ;;
    18) shuffle "$wid" "next"                 ;;
    19) shuffle "$wid" "$wid"                 ;;
  esac
done
