#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# focus a window when it is created
# depends on: wew focus.sh

wew | while IFS=: read ev wid; do
    case $ev in
        # occurs on mapping requests
        19) if ! xwininfo -id "$wid" | grep mpv; then
              wattr o "$wid" || ~/local/cfg/wmutils/focus "$wid"
            fi ;;
    esac
done
