#!/usr/bin/env bash
# Requires https://github.com/wmutils

declare width heigh gaps
source "$XDG_CONFIG_HOME"/wmutils/size

[[ ! $width && $heigh ]] && exit 1

screen_dimensions() {
   dispid=$(lsw -r)
   printf '%s %s\n' "$(wattr w "$dispid")" "$(wattr h "$dispid")"
}

list_windows() {
   local wname
   while read -r id; do
      wname=$(xwininfo -id "$id" | awk '/Window id:/{print $NF}')
      [[ ! $wname ]] && break
      case ${wname//\"/} in
        *.pdf|*.epub|*.djvu|Zathura|NVIM|name\)|w3m)
          wname="$(wattr w "$id") $(( heigh / 2 )) $(wattr w "$id") $(( heigh - gaps )) $id" ;;
         abduco)
           wname="400 228 450 257 $id" ;;
         mpv)
           # We want our movies to take up as much space as they can!
           wname="$(wattr w "$id") $(wattr h "$id") $width $heigh $id" ;;
          float) break ;;
         *)
           wname="400 228 450 257 $id" ;;
      esac  
      printf '%s\n' "$wname"
   done
}

## Main ##
lsw | list_windows | ~/local/cfg/wmutils/bin_pack -x "$width" -y "$heigh" -g "$gaps" | while read -r x y w h wid; do
  wtp "$x" "$y" "$w" "$h" "$wid"
done
