#!/usr/bin/env bash
# Requires https://github.com/wmutils

screen_dimensions() {
   dispid=$(lsw -r)
   printf '%s %s\n' "$(wattr w "$dispid")" "$(wattr h "$dispid")"
}

list_windows() {
   local wname
   while read -r id; do
      wname=$(xwininfo -id "$id" | awk '/Window id:/{print $NF}')
      [[ ! $wname ]] && break
      case ${wname//\"/} in
        Zathura|NVIM|name\))
            wname="$(wattr w "$id") $(( 2 + $(wattr h "$(lsw -r)") / 2 )) $(wattr w "$id") $(wattr h "$(lsw -r)") $id" ;;
         abduco)
           wname="400 225 450 338 $id" ;;
         mpv)
           wname="$(wattr w "$id") $(wattr h "$id") $(wattr w "$(lsw -r)") $(wattr h "$(lsw -r)") $id" ;;
          float) break ;;
         *)
           wname="400 225 450 $(( $(wattr h "$(lsw -r)") / 2 )) $id" ;;
      esac  
      printf '%s\n' "$wname"
   done
}
## Main ##
lsw | list_windows | ~/local/cfg/wmutils/bin_pack -x 1920 -y 1080 | while read -r x y w h wid; do
   wtp "$x" "$y" "$w" "$h" "$wid"
done
