#!/usr/bin/env bash
# Handle open -s && open -t with bemenu
# :bind o spawn --userscript ~/path/to/userscripts/qutedmenu
# :bind O spawn --userscript ~/path/to/userscripts/qutedmenu -O

# This assumes the following files are populated
readonly optsfile="${XDG_CONFIG_HOME:-$HOME/.config}"/dmenu/bemenucolors
if [[ -e "${XDG_CONFIG_HOME:-$HOME/.config}"/dmenu/font ]]; then
    read -r font < "${XDG_CONFIG_HOME:-$HOME/.config}"/dmenu/font
fi
# Example options file

# opts=(
#    --fn "$font" -p 'Run'
#    --tf '#a89984' --tb '#fbf1c7'
#    --nf '#fbf1c7' --nb '#282828'
#    --hf '#fbf1c7' --hb '#928374'
#    --scf '#cc241d' --scb '#cc241d'
#    )

get_options() {
    if [[ -e "$font" ]]; then
        opts+=( -fn "$font" )
    fi

    if [[ -e "$optsfile" ]]; then
        # Parse optsfile
        source "$optsfile"
    fi
}

create_menu() {
    while read -r url; do
        printf -- '%s\n' "${url##*\ }"
    done < "${XDG_CONFIG_HOME:-$HOME/.config}"/qutebrowser/quickmarks

    while read -r url; do
        printf -- '%s\n' "${url:11}"
    done < "${XDG_DATA_HOME:-$HOME/.local/share}"/qutebrowser/history
    }

get_selection() {
    opts+=( -p "Qutebrowser" )
    create_menu | bemenu -l 10 "${opts[@]}"
}

# Main

get_options

url="$(get_selection)"

if [[ "$url" ]]; then
    qutebrowser "$1" "$url"
fi
