#!/bin/sh
X11=${X11FSDIR:-~/run/x11}

read -r title < ~/run/x11/"$1"/title

case "$title" in
  *mpv)              printf '%s\n' "1" > $X11/$1/group ;;
  *w3m|*browse)      printf '%s\n' "2" > $X11/$1/group ;;
  *NVIM)             printf '%s\n' "3" > $X11/$1/group ;;
  *mutt|*newsbeuter) printf '%s\n' "4" > $X11/$1/group ;;
  *irc)              printf '%s\n' "5" > $X11/$1/group ;;
  *Zathura)          printf '%s\n' "6" > $X11/$1/group ;;
esac

echo "$1" > $X11/focused
