#!/bin/sh
#
# z3bra - 2014 (c) wtfpl

X11=${X11FSDIR:-~/run/x11}

# get current window id
read -r CUR < $X11/focused

right() {
  lsw | xargs wattr xi | sort -nr | sed "/$CUR/d;1s/^[0-9]* //p;d"
}

left() {
  lsw | xargs wattr xi | sort -n | sed "/$CUR/d;1s/^[0-9]* //p;d"
}

up() {
  lsw | xargs wattr yi | sort -nr | sed "/$CUR/d;1s/^[0-9]* //p;d"
}

down() {
  lsw | xargs wattr yi | sort -n | sed "/$CUR/d;1s/^[0-9]* //p;d"
}

case $1 in
  l) wid=$(right)             ;;
  j) wid=$(down)              ;;
  h) wid=$(left)              ;;
  k) wid=$(up)                ;;
  *) [ -d $X11/$1 ] && wid=$1 ;;
esac

# exit if we can't find another window to focus
test -z "$wid" && echo "$(basename $0): can't find a window to focus" >&2 && exit 1
echo "$wid" > ~/run/x11/focused  # set focus on it
