#!/usr/bin/env bash

X11=${X11FSDIR:-~/run/x11}
DIR=$XDG_CONFIG_HOME/x11fs
# Number of groups
panels=6
declare -a item
barrun () {
  cd $X11
  local result
  for (( i = 1; i <= $panels; i++ )); do
    if grep -q $i active; then
      item[$i]="◉"
    elif grep -q "$i" inactive; then
      item[$i]="◍"
    else
      item[$i]="◌"
    fi
    result+=${item["$i"]}
  done

  printf '%s\n' "%{c}—${result[@]}—" > /tmp/panel
}

cat $X11/event | while read -r ev; do
  case $ev in
    MAP*)     $DIR/wshuf && barrun            
              $DIR/focus ${ev#*\ }   ;;
    UNMAP*)   $DIR/wshuf && barrun            
              $DIR/focus ${ev#*\ }   ;;
    CREATE*)  $DIR/autotag ${ev#*\ } 
              wait
              $DIR/wshuf             ;;
    DESTROY*) $DIR/wshuf             ;;
  esac
done
